module.exports = {
  browser_download_1: false,
  browser_download_2: false,
  darktheme: false,
  extentions: false,
  finish_mail: false,
  captcha_mail: false,
  headless: false,
  images_styles: false,
  tabs: 2,
  relevance: 6,
  walmart_ca_delivery:"6.00",
  walmart_ca_free_shipping_on: "50.00",
  walmart_com_delivery:"6.00",
  walmart_com_free_shipping_on: "50.00",
  walmart_ca_retailer_only: true,
  walmart_com_retailer_only: true,
  bedbathandbeyond_ca_delivery:"6.00",
  bedbathandbeyond_ca_free_shipping_on: "50.00",
  bedbathandbeyond_com_delivery:"6.00",
  bedbathandbeyond_com_free_shipping_on: "50.00",
  amazon_ca_taxes: "28.0",
  amazon_com_taxes: "28.0",
  min_dif_percentage: 0,
  max_dif_percentage: 0,
  min_dif_price: 20,
  max_dif_price: 0,
  min_identity: 60,
  results_per_page: 50,
  chrome_path: "/usr/bin/chromium-browse",
  amazon_rank_only: false,
  match_only: false,
  match_identity: false,
  hide_amazon_listing: false,
  hide_inaddible: false,
  hide_exeption: false,
  hide_listed: false,
  match_profit: false,
  localization: "en",
  watch_notification_email: '',
  parsing_notification_email: '',
  watch_period: 12,
  watcher_delay: 0,
  captcha_continue_timeout: 10,
  amazon_store_name: ''
}
